[tool.poetry]
name = "extreme-weather-db"
version = "0.1.0"
description = ""
authors = ["Tilmann Diepenbruck <tdiepenb@smail.uni-koeln.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
